ctfd:
  name: Demo
  admin_user: admin
  admin_email: cyber@es.aau.dk
  admin_pass: Zg5txAyg2WNmUt6vz7ep
guac:
  admin_user: guacadmin
  admin_pass: admin
  host: localhost
  port: 80
revproxy:
  host: localhost
