ctfd:
  name: Demo
  admin_user: admin
  admin_email: cyber@es.aau.dk
  admin_pass: Zg5txAyg2WNmUt6vz7ep
guacamole:
  admin_pass: admin
  host: localhost
  port: 80
revproxy:
  host: localhost
lab:
  capacity:
    buffer: 1
    max: 10
  frontend:
    directory: /scratch/git/training-platform/exercises
    ova_files:
    - aau-kali.ova
  exercise:
  - name: SQL Injection
    tags:
    - sql
    docker:
    - image: registry.sec-aau.dk/aau/sql-client
      memoryMB: 50
      flag:
      - name: Web server login
        env: INTERNAL_FLAG
        default: c5b0238c-f504-4ade-8075-3afb71e88cf6
        points: 5
      - name: SQL injection
        env: DB_FLAG
        default: 334637ad-2c51-45dd-89d9-9b7c7155b366
        points: 15
    - image: registry.sec-aau.dk/aau/sql-server
      memoryMB: 85
      dns:
      - name: netsec-forum.dk
        record: A
      flag:
      - name: Network sniffing
        env: FLAG
        default: 613ee1e1-ab15-4c0e-b324-3f2a6eee25f2
        points: 5
  - name: Cross-Site Scripting
    tags:
    - xss
    docker:
    - image: registry.sec-aau.dk/aau/xss-client
      memoryMB: 512
      env:
      - env: TARGET_URL
        value: https://dogshare.com
      - env: USERNAME
        value: whatever
      - env: PASSWORD
        value: pas122nes
    - image: registry.sec-aau.dk/aau/xss-server
      memoryMB: 85
      dns:
      - name: dogshare.com
        record: A
      flag:
      - name: Cross-site scripting
        env: FLAG
        default: 8bf23f64-9150-45a4-8901-a157896c73a4
        points: 15
  - name: Network Scanning
    tags:
    - scan
    docker:
    - image: registry.sec-aau.dk/aau/hidden-server
      flag:
      - name: Network scanning
        env: FLAG
        default: 8d6bd6bb-c773-4e62-9c4a-620b331703eb
        points: 5
  - name: Heartbleed Exploit
    tags:
    - heart
    - hb
    docker:
    - image: registry.sec-aau.dk/aau/heartbleed
      memoryMB: 100
      flag:
      - name: Heartbleed
        env: FLAG
        default: d346b8aa-469f-42e3-a8ed-4e0d004c9938
        points: 8
      dns:
      - name: cph-sec.com
        record: A
  - name: Man-in-the-Middle
    tags:
    - mitm
    docker:
    - image: registry.sec-aau.dk/aau/mitm-server
      memoryMB: 100
      dns:
      - name: secureshare.com
        record: A
    - image: registry.sec-aau.dk/aau/mitm-client
      memoryMB: 75
      env:
      - env: TARGET_URL
        value: https://secureshare.com
      flag:
      - name: Man in the middle
        env: FLAG
        default: 2bd60c1f-530a-4287-af42-1b869b78e288
        points: 15
